os:
    - linux
    - osx

env:
    - SUITE=tests
    - SUITE=examples
    - SUITE=benchmarks

language:
    - cpp

before_install:
    - ./ci/before_install.sh

install:
    - ./ci/install.sh

before_script:
    - mkdir build && cd build

script:
    - ../ci/script.sh
