language: c
compiler:
- gcc
- clang
before_install:
- echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
- sudo apt-get update -qq
- sudo apt-get install cmake
- sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev
script: mkdir build && cd build && cmake ../ && make
notifications:
  slack:
    secure: IA4WTzrZBxyb1bvgKPq9ZLotP+TC/+t1b3LzL1XXXj+MWa6b+It4kiuuKmbPGFxIaZTdsHcDKWAOXPOsLie2XQKE6la2JvWKyqwqmPLV/1pRe0SI5Iq7/MR8++iyq6169bespg/ZF/8mwMN6Xk1x4H2i0PRA3lIY3U0udh1EXVs=
