sudo: false
language: c
compiler:
- gcc
install:
  - wget https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.7.1.tar.gz?raw=true --output-document=cpputest-3.7.1.tar.gz
  - tar -xzf cpputest-3.7.1.tar.gz
  - pushd cpputest-3.7.1/build && autoreconf .. -i && ../configure --prefix=$HOME/cpputest && make && make install
  - export CPPUTEST_HOME=$HOME/cpputest
  - popd
script: mkdir build && cd build && cmake ../ && make && make test
notifications:
  webhooks:
      urls:
          - https://webhooks.gitter.im/e/6de15e574ba6be5f3b79
      on_success: change
      on_failure: always
  slack:
      secure: IA4WTzrZBxyb1bvgKPq9ZLotP+TC/+t1b3LzL1XXXj+MWa6b+It4kiuuKmbPGFxIaZTdsHcDKWAOXPOsLie2XQKE6la2JvWKyqwqmPLV/1pRe0SI5Iq7/MR8++iyq6169bespg/ZF/8mwMN6Xk1x4H2i0PRA3lIY3U0udh1EXVs=
addons:
    code_climate:
        repo_token: 19c61f1e9c92ca3aa28ac4290ed248100a7966ae7f8ee0139aec55866a3618c6

