language: c
compiler:
- gcc
install:
- wget https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.6.tar.gz?raw=true -O cpputest-3.6.tar.gz
- tar -xzvf cpputest-3.6.tar.gz
- pushd cpputest-3.6/build && autoreconf .. -i && ../configure --prefix=/usr/local/ && make && sudo make install
- export CPPUTEST_HOME=/usr/local/
- popd
script: mkdir build && cd build && cmake ../ && make && make test
notifications:
  webhooks:
      urls:
          - https://webhooks.gitter.im/e/6de15e574ba6be5f3b79
      on_success: change
      on_failure: always
  slack:
      secure: IA4WTzrZBxyb1bvgKPq9ZLotP+TC/+t1b3LzL1XXXj+MWa6b+It4kiuuKmbPGFxIaZTdsHcDKWAOXPOsLie2XQKE6la2JvWKyqwqmPLV/1pRe0SI5Iq7/MR8++iyq6169bespg/ZF/8mwMN6Xk1x4H2i0PRA3lIY3U0udh1EXVs=
