language: c
compiler:
- gcc
- clang
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y cpputest
script: mkdir build && cd build && cmake ../ && make && make test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6de15e574ba6be5f3b79
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack:
    secure: IA4WTzrZBxyb1bvgKPq9ZLotP+TC/+t1b3LzL1XXXj+MWa6b+It4kiuuKmbPGFxIaZTdsHcDKWAOXPOsLie2XQKE6la2JvWKyqwqmPLV/1pRe0SI5Iq7/MR8++iyq6169bespg/ZF/8mwMN6Xk1x4H2i0PRA3lIY3U0udh1EXVs=
